plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-tactile
-[<h1 id="cheap-nintendo-switch-games-for-rental-here">Cheap Nintendo Switch games for rental here</h1>]
